### PR TITLE
Remove the style check

### PR DESCRIPTION
**Pull request by WilliamJamieson**
This is no being performed by the `pre-commit.ci` bot as a different CI job.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Note, an update to the `Required` CI jobs will need to be done after this is merged. It needs to remove the `check / check-style (ubuntu-latest)` job and replace it with `pre-commit.ci - pr`

**Comment by WilliamJamieson** [comment]
No regression tests are needed here as this only touches the GitHub CI.

**Review by PaulHuwe — APPROVED** [review]
LGTM

**Review by PaulHuwe — APPROVED** [review]
LGTM

**Pull request merged**
