### PR TITLE
Remove all hints of roman_datamodels units

### PR DESCRIPTION
**Pull request by WilliamJamieson**
This PR makes the necessary changes to `roman_datamodels` to support spacetelescope/rad#248.

**Checklist**
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
The CI failures seem to be a github issue not a test failure. It seems like the action run was terminated in the middle by some GitHub error. GitHub has been experiencing CI issues for the past few days.

**Review by PaulHuwe — APPROVED** [review]
LGTM - I have updated my L3 PRs to match this.

**Comment by WilliamJamieson** [comment]
Close/reopen to trigger CI that did not run due to GitHub system issues today.

**Comment by WilliamJamieson** [comment]
Test failures will be fixed by #174.

**Pull request merged**
