### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by larrybradley**
The second commit also replaces tabs with spaces in `using_datamodels.rst`.

**Checklist**
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

### CODE REVIEW

**Review by PaulHuwe — APPROVED** [review]
LGTM

**Comment by larrybradley** [comment]
The `pre-commit` `codespell` test failed due to a typo in the changelog, so I just fixed that one too. :smile:

**Comment by PaulHuwe** [comment]
Let me know when you are ready for this to be merged.

**Comment by larrybradley** [comment]
Merge away!

**Pull request merged**
