### PR TITLE
RCAL-436 Move Maker Utilities

### PR DESCRIPTION
**Pull request by PaulHuwe**
Moving datamodel maker utilities from testing/utils to the main directory in order to better reflect their usage. As part of that,  also split random functions out to their own utility file and linking to them.

### CODE REVIEW

**Comment by schlafly** [comment]
This looks good to me.  What do we expect it to break?
- romancal?
- INS wfisim wrapper
- simulator
- ?

**Comment by PaulHuwe** [comment]
That's the list for packages. Everything else would be people's personal preferences, any old instructional notebooks lying around, etc.

**Review by mairanteodoro — APPROVED** [review]
Looking good to me.

**Review by ddavis-stsci — APPROVED** [review]
Looks good.

**Review by schlafly — APPROVED** [review]

**Pull request merged**
