### PR TITLE
RCAL-357 Add a test for `filetype.py` to `roman_datamodels`

### PR DESCRIPTION
**Pull request by zacharyburnett**
[RCAL-357](https://jira.stsci.edu/browse/RCAL-357)

### CODE REVIEW

**Comment by ddavis-stsci** [comment]
Unfortunately, I'm having trouble running the test...
```
            return "asn"

>       raise ValueError(f"Cannot get file type of {str(init)}")
E       ValueError: Cannot get file type of /Users/ddavis/src/Roman/roman_datamodels/tests/data/empty.json

../../../miniconda3/envs/rcal_dev/lib/python3.10/site-packages/roman_datamodels/filetype.py:51: ValueError
===================================================== short test summary info =====================================================
FAILED tests/test_filetype.py::test_filetype - ValueError: Cannot get file type of /Users/ddavis/src/Roman/roman_datamodels/test...
======================================================== 1 failed in 0.45s ========================================================
```
but the file does appear to be in the correct spot,
(rcal_dev) bash>ll /Users/ddavis/src/Roman/roman_datamodels/tests/data/empty.json
-rw-r--r--  1 ddavis  STSCI\science  0 Aug 29 15:50 /Users/ddavis/src/Roman/roman_datamodels/tests/data/empty.json

**Comment by zacharyburnett** [comment]
> Unfortunately, I'm having trouble running the test...
> 
> ```
>             return "asn"
> 
> >       raise ValueError(f"Cannot get file type of {str(init)}")
> E       ValueError: Cannot get file type of /Users/ddavis/src/Roman/roman_datamodels/tests/data/empty.json
> 
> ../../../miniconda3/envs/rcal_dev/lib/python3.10/site-packages/roman_datamodels/filetype.py:51: ValueError
> ===================================================== short test summary info =====================================================
> FAILED tests/test_filetype.py::test_filetype - ValueError: Cannot get file type of /Users/ddavis/src/Roman/roman_datamodels/test...
> ======================================================== 1 failed in 0.45s ========================================================
> ```
> 
> but the file does appear to be in the correct spot, (rcal_dev) bash>ll /Users/ddavis/src/Roman/roman_datamodels/tests/data/empty.json -rw-r--r-- 1 ddavis STSCI\science 0 Aug 29 15:50 /Users/ddavis/src/Roman/roman_datamodels/tests/data/empty.json

I ran the tests on an editable installation and also on a fresh Conda environment with `pip install ".[test]"` but the tests passed both times without issue. It might be an issue with the file packaging.

**Comment by ddavis-stsci** [comment]
Yep, I only did that for 356 and forgot for 357, sigh.

**Review by ddavis-stsci — APPROVED** [review]
LGTM

**Pull request merged**
