### PR TITLE
added asdf info method introspection for DNode an LNode classes

### PR DESCRIPTION
**Pull request by perrygreenfield**
This PR allows the asdf `node` method to show the contents of Roman datafiles whereas previously it didn't since it would treat any tag class as opaque (the Roman tree structure is primarily made of tag classes unlike JWST tree structures). The referenced asdf PR is asdf-format/asdf#1052, and for this functionality to work, that PR must be installed.

### CODE REVIEW

**Comment by ddavis-stsci** [comment]
I don't know if this is a feature or a bug but the info and search methods are not available when using roman_datamodels open,
```
from roman_datamodels import datamodels as rdm
rdata = rdm.open('r0000101001001001001_01101_0001_WFI01_cal.asdf')
rdata.info()
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ddavis/src/Roman/roman_datamodels/src/roman_datamodels/datamodels.py", line 187, in __getattr__
    return getattr(self._instance, attr)
  File "/Users/ddavis/src/Roman/roman_datamodels/src/roman_datamodels/stnode.py", line 156, in __getattr__
    raise AttributeError(f"No such attribute ({key}) found in node")
AttributeError: No such attribute (info) found in node

Should this be a separate ticket?

**Comment by perrygreenfield** [comment]
Funny you should mention that. It was added this morning (though there is a detail to be fixed with regard to searches that will result in an update to the asdf PR).

**Comment by ddavis-stsci** [comment]
If I open the file using asdf.open
import asdf
>>> rdata_asdf = asdf.open('r0000101001001001001_01101_0001_WFI01_cal.asdf')
>>> rdata_asdf.info()
root (AsdfObject)
├─asdf_library (Software)

but the search method does no appear to include the roman information,
>>> rdata_asdf['roman']['meta']['exposure']['sca_number']
1
>>> rdata_asdf.search(value=1)
No results found.

Am I missing something here? I can do the search on the example files with no issues,
t_asdf.search(value=1)
root (AsdfObject)
└─list (list)
  └─[1] (dict)
    └─index (int): 1
(From the search tests directory)

**Comment by perrygreenfield** [comment]
In previous tests I had noticed that values were not being properly picked up in searches. So fix was made to asdf for searches that would affect roman files. I don't know if it is the problem you ran into, but it would be good to update asdf (and roman_datamodels, for the minor test addition) and see if this affects the above problem.

**Review by ddavis-stsci — APPROVED** [review]
Looks good, the search and info functions work from roman_datamodels using the open function. e.g.
```
rdata = rdm.open('r0000101001001001001_01101_0001_WFI01_cal.asdf')
rdata.search(key='velocity')
root (AsdfObject)
└─roman (WfiImage)
  └─meta (dict)
    ├─ephemeris (Ephemeris)
    │ ├─velocity_x (int): 10
    │ ├─velocity_y (int): 2
    │ └─velocity_z (float): 3.5
    └─velocity_aberration (VelocityAberration)
```

**Comment by eslavich** [comment]
Rebasing in the latest main branch will hopefully fix the tests...

**Review by eslavich — APPROVED** [review]
LGTM!

**Pull request merged**
