### PR TITLE
metadata for release `0.21.0`

### PR DESCRIPTION
**Pull request by zacharyburnett**

### CODE REVIEW

**Review by PaulHuwe — APPROVED** [review]
I assume you will re-run the tests once the RAD release is done?

**Comment by PaulHuwe** [comment]
No, that was just added.

**Comment by PaulHuwe** [comment]
I see the issue.. resolving now.

**Comment by PaulHuwe** [comment]
I merged a PR, rerunning the tests.

**Comment by zacharyburnett** [comment]
looks like that fixed it!

**Pull request merged**
