### PR TITLE
replace usages of ``copy_arrays`` with ``memmap``

### PR DESCRIPTION
**Pull request by zacharyburnett**
follow-on to https://github.com/asdf-format/asdf/pull/1797

**Checklist**
- [x] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

### CODE REVIEW

**Comment by braingram** [comment]
Bumping the asdf version to at least 3.1.0 should fix the oldest deps:
https://github.com/spacetelescope/roman_datamodels/blob/1b298e10221c293fe82fdc7d75603da9e816e89f/pyproject.toml#L16

**Comment by PaulHuwe** [comment]
Can you please add a RCAL regression test URL as well?

**Comment by zacharyburnett** [comment]
> Can you please add a RCAL regression test URL as well?

RCAL regtest running at https://github.com/spacetelescope/RegressionTests/actions/runs/10042547798 with this branch installed

**Comment by zacharyburnett** [comment]
a few failures in RCAL regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/10042547798/attempts/2#summary-27759909972

**Comment by braingram** [comment]
> a few failures in RCAL regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/10042547798/attempts/2#summary-27759909972

The failures are unrelated (they're expected and caused by https://github.com/spacetelescope/romancal/pull/1241).

Would you re-run them? I okified the results from a different run but I think that wasn't until after your tests had run.

**Comment by zacharyburnett** [comment]
sure, rerunning here: https://github.com/spacetelescope/RegressionTests/actions/runs/10042547798

**Comment by braingram** [comment]
The oldest deps failure should be solvable with a bump to the gwcs version:
https://github.com/spacetelescope/roman_datamodels/actions/runs/10045391464/job/27762571944?pr=360#step:10:292

**Comment by braingram** [comment]
Sorry for the back and forth but this will likely need another run. It turns out that some of the roman tests continue to fail after the first "okify": https://github.com/spacetelescope/romancal/issues/1325 I have a run on main to test if the current "okified" results pass. I'll post and update here once the run on main passes.

**Comment by braingram** [comment]
I re-ran the regtests for this PR (now that the romancal main ones are passing):
https://github.com/spacetelescope/RegressionTests/actions/runs/10042547798

The run with this PR shows all passing tests.

**Review by braingram — APPROVED** [review]
LGTM!

**Pull request merged**
